### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by JustinAzoff** [ncsa/dumbno#10]
the code that generates the acl commands needs to be aware of ipv6. the rules themselves will be the same, but you can't add a v6 rule to a v4 acl.

**Comment by JustinAzoff** [comment]
https://github.com/ncsa/dumbno/tree/feature-ipv6 now contains a branch with untested ipv6 support.

**Comment by dopheide-esnet** [comment]
First thing I noticed was in the 'setup' routine, there was still a reference to self.families, which no longer exists.

Now I'm just getting 'no route to host' errors that I need to resolve.  There is a route and dumbno v4 works fine, just need to dig more.

**Comment by dopheide-esnet** [comment]
Past that, I forgot I was using https instead of http.  Maybe the self.uri can test for that.

**Comment by dopheide-esnet** [comment]
INFO:dumbno:Started
INFO:dumbno:Ready..
Traceback (most recent call last):
  File "./dumbno.py", line 412, in <module>
    main()
  File "./dumbno.py", line 409, in main
    launch(config, setup=setup)
  File "./dumbno.py", line 390, in launch
    svr.run()
  File "./dumbno.py", line 320, in run
    self.check()
  File "./dumbno.py", line 313, in check
    self.mgr.remove_expired()
  File "./dumbno.py", line 245, in remove_expired
    self.dump(to_remove_flat, op="REMOVE")
  File "./dumbno.py", line 156, in dump
    x['name'] = x['acl']['name']
TypeError: tuple indices must be integers, not str

This one I'm not sure how to fix.

**Comment by JustinAzoff** [comment]
Ah, that's a stupid error on my part.

**Comment by JustinAzoff** [comment]
Forgot to close this..  We've been running this branch for a few months now even though we don't have much v6, and I assume it works for you :-)
